export class CodeGen {
  constructor(ast) {
    this.ast = ast;

    this.css = `#container>.answered,#container>button{animation:.6s cubic-bezier(.38,.97,.56,.76) .1s forwards show;opacity:0;transform:rotateX(-90deg)}#container,#container>button,#container>button:hover{font-family:"Special Elite",system-ui}body{width:100vw;height:100vh;overflow-x:hidden;margin:5rem 10rem}#container{width:calc(100vw - 20rem);font-size:20px}#container>*{margin-top:0;margin-bottom:7px}#container>button{width:100%;border:none;background:0 0;color:#414141;font-size:15px;transform-origin:top center}#container>.answered{transform-origin:top center;color:gray;margin-top:10px;margin-bottom:10px}#container>button:hover{color:#4b4b4b;font-size:18px}@keyframes show{100%{opacity:1;transform:none}}`;
    this.js =
      `const ast=` +
      JSON.stringify(this.ast, null, 0) +
      `window.container=document.getElementById("container"),window.text=(e,t)=>{let n=document.createElement("p");container.appendChild(n);let c=[e],a=50;var i,r=0,o=c[0].length;let l=20;var s=0,u="";function $(){u=" ",i=Math.max(0,r-l);for(var e=n;i<r;)u+=c[i++]+"<br />";e.innerHTML=u+c[r].substring(0,s)+"_",s++==o?(s=0,++r!=c.length?(o=c[r].length,setTimeout($,500)):(e.innerHTML=u+c[r-1].substring(0,o),"function"==typeof t&&t())):setTimeout($,a)}$()},window.choice=(e,t)=>{let n=document.createElement("button");n.innerHTML=e,n.onclick=()=>{Array.prototype.slice.call(container.getElementsByTagName("button"),0).forEach(e=>{e.remove()});let e=document.createElement("p");e.innerHTML=n.innerHTML,e.class="answered",window.container.appendChild(e),window.execute(0,t)},container.appendChild(n)},window.diversion=e=>{e&&e()},window.end=()=>{throw window.text("--- The End ---"),"Thanks for playing!!!"},window.execute=(index,ast=ast)=>{if(ast[index].type)switch(ast[index].type){case"Var":eval(ast[index].name+"="+ast[index].value),window.execute(ast[index+1]);break;case"Text":window.text(ast[index].content,()=>{window.execute(ast[index+1])});break;case"Diversion":window.diversion(window.ast[index].section),window.execute(ast[index+1]);break;case"Section":eval("function"+window.ast[index].name+"(){const localAst="+JSON.stringify(window.ast[index].body,null,0)+";window.execute(0,localAst);}"),window.execute(ast[index+1]);break;case"Choice":window.choice(window.ast[index].content),window.execute(ast[index+1])}},window.execute(0,ast);`;
    this.html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Iris</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet"><style>${this.css}</style></head><body><div id="container"></div><script>${this.js}</script></body></html>`;
  }
}
